# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 
    url: /
    identifier: home
    pre: <i class="fa-solid fa-house"></i>
    weight: 1
  - name: News
    url: post
    pre: <i class="fa-solid fa-newspaper" style="padding-right:5px"></i>
    weight: 10
  - name: People
    url: people
    identifier: people
    pre: <i class="fa-solid fa-users" style="padding-right:5px"></i>
    weight: 20
  - name: Research
    url: research
    identifier: research
    pre: <i class="fa-solid fa-book" style="padding-right:5px"></i>
    weight: 30
  - name: Events
    url: event
    identifier: events
    pre: <i class="fa-regular fa-calendar" style="padding-right:5px"></i>
    weight: 40
  - name: Teaching
    url: teaching
    identifier: teaching
    pre: <i class="fa-solid fa-building-columns" style="padding-right:5px"></i>
    weight: 50
  - name: Thesis
    url: thesis
    identifier: thesis
    pre: <i class="fa-solid fa-book-open" style="padding-right:5px"></i>
    weight: 60
  - name: Contact
    url: contact
    identifier: contact
    pre: <i class="fa-solid fa-circle-info" style="padding-right:5px"></i>
    weight: 100
